---
sudo: required
dist: trusty
language: ruby
cache: bundler
before_install:
  - "wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && sudo dpkg -i pdk.deb && rm pdk.deb"
script:
  - 'pdk $CHECK'
bundler_args: --without system_tests
env:
  - PUPPET_GEM_VERSION="~> 4.0" CHECK="validate"
  - PUPPET_GEM_VERSION="~> 4.0" CHECK="test unit"
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
